# Generated by Django 4.2.5 on 2023-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=260)),
                ('password', models.CharField(max_length=260)),
            ],
        ),
    ]
